CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY, applied_at INTEGER NOT NULL);
INSERT OR IGNORE INTO schema_versions VALUES(1,unixepoch()*1000);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,theme TEXT NOT NULL DEFAULT 'auto',blocked INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admins(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,totp_secret TEXT NOT NULL,last_totp_step INTEGER NOT NULL DEFAULT -1,role TEXT NOT NULL CHECK(role IN ('owner','manager','questions')),active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN ('guest','admin')),user_id TEXT REFERENCES users(id) ON DELETE CASCADE,admin_id TEXT REFERENCES admins(id) ON DELETE CASCADE,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS challenges(id TEXT PRIMARY KEY,session_hash TEXT NOT NULL,answer_hash TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS rates(key TEXT PRIMARY KEY,count INTEGER NOT NULL,reset_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_rates_reset ON rates(reset_at);
CREATE TABLE IF NOT EXISTS tournaments(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,active INTEGER NOT NULL DEFAULT 1,position INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS questions(id TEXT PRIMARY KEY,tournament_id TEXT NOT NULL REFERENCES tournaments(id),letter TEXT NOT NULL,text TEXT NOT NULL UNIQUE,answer TEXT NOT NULL,difficulty TEXT NOT NULL CHECK(difficulty IN ('easy','medium','hard')),status TEXT NOT NULL CHECK(status IN ('published','hidden')),source TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_questions_pool ON questions(tournament_id,status,letter,difficulty);
CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES users(id),config TEXT NOT NULL,state TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_rooms_owner ON rooms(owner_id,status);
CREATE TABLE IF NOT EXISTS members(room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,team INTEGER NOT NULL CHECK(team IN (1,2)),name TEXT NOT NULL,kicked INTEGER NOT NULL DEFAULT 0,joined_at INTEGER NOT NULL,PRIMARY KEY(room_id,user_id));
CREATE TABLE IF NOT EXISTS matches(id TEXT PRIMARY KEY,room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,round INTEGER NOT NULL,winner INTEGER NOT NULL,board TEXT NOT NULL,finished_at INTEGER NOT NULL,UNIQUE(room_id,round));
CREATE TABLE IF NOT EXISTS match_players(match_id TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,won INTEGER NOT NULL,PRIMARY KEY(match_id,user_id));
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,message TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_events_room ON events(room_id,id);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS football_entities(id TEXT PRIMARY KEY,entity_type TEXT NOT NULL,name_ar TEXT NOT NULL,name_en TEXT NOT NULL,image_key TEXT,image_source TEXT,image_license TEXT,fallback TEXT NOT NULL,metadata TEXT NOT NULL DEFAULT '{}',updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_football_entities_type ON football_entities(entity_type);
CREATE TABLE IF NOT EXISTS football_relations(id TEXT PRIMARY KEY,from_entity_id TEXT NOT NULL REFERENCES football_entities(id),to_entity_id TEXT NOT NULL REFERENCES football_entities(id),relation_type TEXT NOT NULL,starts_at TEXT,ends_at TEXT,metadata TEXT NOT NULL DEFAULT '{}',source TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_football_relations_from_type ON football_relations(from_entity_id,relation_type);
CREATE INDEX IF NOT EXISTS idx_football_relations_to_type ON football_relations(to_entity_id,relation_type);
CREATE TABLE IF NOT EXISTS mini_game_rounds(id TEXT PRIMARY KEY,game_slug TEXT NOT NULL,difficulty TEXT NOT NULL,prompt TEXT NOT NULL,solution TEXT NOT NULL,accepted TEXT NOT NULL DEFAULT '[]',explanation TEXT NOT NULL DEFAULT '',visual_data TEXT NOT NULL DEFAULT '{}',source TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'published',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_mini_game_rounds_pool ON mini_game_rounds(game_slug,status,difficulty);
CREATE TABLE IF NOT EXISTS mini_game_rooms(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES users(id),config TEXT NOT NULL,state TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_mini_game_rooms_owner ON mini_game_rooms(owner_id,status);
CREATE TABLE IF NOT EXISTS mini_game_members(room_id TEXT NOT NULL REFERENCES mini_game_rooms(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,team INTEGER NOT NULL CHECK(team IN (1,2)),name TEXT NOT NULL,kicked INTEGER NOT NULL DEFAULT 0,joined_at INTEGER NOT NULL,last_seen INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(room_id,user_id));
CREATE INDEX IF NOT EXISTS idx_mini_game_members_seen ON mini_game_members(room_id,last_seen);
CREATE TABLE IF NOT EXISTS mini_game_events(id INTEGER PRIMARY KEY AUTOINCREMENT,room_id TEXT NOT NULL REFERENCES mini_game_rooms(id) ON DELETE CASCADE,message TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_mini_game_events_room ON mini_game_events(room_id,id);

CREATE TABLE IF NOT EXISTS visual_questions(question_id TEXT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,kind TEXT NOT NULL CHECK(kind IN ('career','guess_club_nationalities','guess_nation_clubs')),payload TEXT NOT NULL CHECK(json_valid(payload)),verified_at TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS visual_assets(id TEXT PRIMARY KEY,content_type TEXT NOT NULL,relative_path TEXT NOT NULL UNIQUE,sha256 TEXT NOT NULL UNIQUE,license TEXT NOT NULL,source TEXT NOT NULL,created_at INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS football_import_batches(id TEXT PRIMARY KEY,source TEXT NOT NULL,snapshot_date TEXT NOT NULL,sha256 TEXT NOT NULL,entities_added INTEGER NOT NULL,relations_added INTEGER NOT NULL,images_missing INTEGER NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_football_import_batches_date ON football_import_batches(created_at DESC);

CREATE TABLE IF NOT EXISTS football_participant_snapshots(competition_id TEXT NOT NULL REFERENCES football_entities(id),season TEXT NOT NULL,team_ids TEXT NOT NULL CHECK(json_valid(team_ids)),source TEXT NOT NULL,verified_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','reviewed')),PRIMARY KEY(competition_id,season));
CREATE TABLE IF NOT EXISTS football_squad_snapshots(team_id TEXT NOT NULL REFERENCES football_entities(id),competition_id TEXT NOT NULL REFERENCES football_entities(id),season TEXT NOT NULL,player_ids TEXT NOT NULL CHECK(json_valid(player_ids)),coach_ids TEXT NOT NULL CHECK(json_valid(coach_ids)),source TEXT NOT NULL,verified_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','reviewed')),PRIMARY KEY(team_id,competition_id,season));
CREATE TABLE IF NOT EXISTS football_context_media(id TEXT PRIMARY KEY,entity_id TEXT NOT NULL REFERENCES football_entities(id),team_id TEXT REFERENCES football_entities(id),role TEXT NOT NULL CHECK(role IN ('portrait','flag','emblem','logo')),starts_at TEXT NOT NULL,ends_at TEXT,asset_id TEXT NOT NULL REFERENCES visual_assets(id),review TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(review)),UNIQUE(entity_id,team_id,role,starts_at));
CREATE INDEX IF NOT EXISTS idx_football_context_media_lookup ON football_context_media(entity_id,team_id,role,starts_at,ends_at);
CREATE TABLE IF NOT EXISTS football_fact_records(id TEXT PRIMARY KEY,entity_id TEXT NOT NULL REFERENCES football_entities(id),kind TEXT NOT NULL,context_id TEXT,season TEXT,as_of TEXT NOT NULL,payload TEXT NOT NULL CHECK(json_valid(payload)),source TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','reviewed','unavailable','conflicting')),verified_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_football_facts_entity_kind ON football_fact_records(entity_id,kind,season,as_of);
