import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,existsSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {randomBytes} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile);
const directory=mkdtempSync(resolve(tmpdir(),'huroof-test-'));
process.env.DATA_DIR=directory;process.env.NODE_ENV='test';
const {createApplication}=await import('../server/index.mjs');
const {db,one,many,run}=await import('../server/database.mjs');
const {hash,hmac,token,base32,passwordHash,sealSecret,totp,openSecret}=await import('../server/security.mjs');
const {subscribers,expireBuzzers}=await import('../server/rooms.mjs');
let server,base,roomId,host,player1,player2,observer,ownerAdmin,editorAdmin;
const ORIGIN='http://127.0.0.1:39871';
async function start(){const app=createApplication({origin:ORIGIN});server=app.server;await new Promise(resolve=>server.listen(39871,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}`;}
class Client{
  cookies={};csrf='';user=null;
  async request(path,body,extra={}){const headers={Host:'127.0.0.1:39871',Connection:'close',Cookie:Object.entries(this.cookies).map(([k,v])=>`${k}=${v}`).join('; '),...(body===undefined?{}:{Origin:ORIGIN,'Content-Type':'application/json','X-CSRF-Token':this.csrf}),...extra};const res=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});for(const c of res.headers.getSetCookie()){const [key,value]=c.split(';')[0].split('=');this.cookies[key]=value;}let data;try{data=await res.json();}catch{data=null;}if(data?.csrf)this.csrf=data.csrf;if(data?.user)this.user=data.user;return {status:res.status,data,headers:res.headers};}
  async init(){const r=await this.request('/session');assert.equal(r.status,200,JSON.stringify(r.data));return this;}
  async identity(name){const id=token(18),answer='AB234';run('INSERT INTO challenges VALUES(?,?,?,?)',id,hash(this.cookies.hk_sid),hmac(`${id}:${answer}`),Date.now()+120000);const result=await this.request('/identity',{name,challenge:id,answer});assert.equal(result.status,200,JSON.stringify(result.data));return this;}
  async room(view='host'){const r=await this.request(`/rooms/${roomId}?view=${view}`);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;}
  async action(action,extra={}){const current=await this.room();const r=await this.request(`/rooms/${roomId}/action`,{action,version:current.version,...extra});assert.equal(r.status,200,JSON.stringify(r.data));return r.data;}
}
before(async()=>{await start();host=await new Client().init();await host.identity('المقدم');player1=await new Client().init();await player1.identity('يزن');player2=await new Client().init();await player2.identity('فهد');observer=await new Client().init();});
after(async()=>{for(const set of subscribers.values())for(const c of set)c.res.end();server.closeAllConnections();await new Promise(r=>server.close(r));db.close();});
test('guest sessions rotate on identity and use HttpOnly, SameSite cookies; challenge is one-use raster',async()=>{const c=await new Client().init(),initial=c.cookies.hk_sid;const challenge=await c.request('/challenge');assert.ok(challenge.data.image.startsWith('data:image/png;base64,'));assert.equal((await c.request('/identity',{name:'تجربة',challenge:challenge.data.id,answer:'WRONG'})).status,400);assert.equal(one('SELECT id FROM challenges WHERE id=?',challenge.data.id),undefined);await c.identity('اسم آمن');assert.notEqual(initial,c.cookies.hk_sid);assert.equal(one('SELECT * FROM sessions WHERE token_hash=?',hash(initial)),undefined);const anonymous=await new Client().request('/session');assert.match(anonymous.headers.get('set-cookie'),/HttpOnly/);assert.match(anonymous.headers.get('set-cookie'),/SameSite=Strict/);});
test('create real persisted room, enter teams and retrieve distinct role views',async()=>{const tournaments=(await host.request('/tournaments')).data;assert.equal(tournaments.length,11);const result=await host.request('/rooms',{teams:[{name:'الصقور',color:'#15803d'},{name:'النجوم',color:'#2563eb'}],size:4,mode:'human',seconds:5,tournaments:tournaments.map(t=>t.id),difficulty:'all',autoReopen:true});assert.equal(result.status,201,JSON.stringify(result.data));roomId=result.data.id;assert.equal(roomId.length,12);assert.equal((await player1.request(`/rooms/${roomId}/join`,{team:1})).status,200);assert.equal((await player2.request(`/rooms/${roomId}/join`,{team:2})).status,200);assert.equal((await host.room()).players.length,2);assert.equal((await observer.room('display')).players,undefined);});
test('unchanged room snapshots are minimal while role authorization still holds',async()=>{
  const latest=await host.room();
  const unchanged=await host.request(`/rooms/${roomId}?view=host&since=${latest.version}`);
  assert.equal(unchanged.status,200);
  assert.equal(unchanged.data.unchanged,true);
  assert.equal(unchanged.data.version,latest.version);
  assert.equal(unchanged.data.board,undefined);
  const forbidden=await player1.request(`/rooms/${roomId}?view=host&since=${latest.version}`);
  assert.equal(forbidden.status,403);
  const nonmember=await observer.request(`/rooms/${roomId}?view=buzzer&since=${latest.version}`);
  assert.equal(nonmember.status,401);
});
test('IDOR, role spoofing, missing CSRF, hostile Origin and CORS are rejected on actual endpoints',async()=>{const room=await host.room();assert.equal((await player1.request(`/rooms/${roomId}?view=host`)).status,403);assert.equal((await player1.request(`/rooms/${roomId}/action`,{action:'select',version:room.version,cell:0,owner_id:host.user.id,role:'host'})).status,403);assert.equal((await observer.request(`/rooms/${roomId}/action`,{action:'restart',version:room.version})).status,401);assert.equal((await host.request(`/rooms/${roomId}/action`,{action:'restart',version:room.version},{'X-CSRF-Token':''})).status,403);const cross=await host.request(`/rooms/${roomId}/action`,{action:'restart',version:room.version},{Origin:'https://evil.example'});assert.equal(cross.status,403);assert.equal(cross.headers.get('access-control-allow-origin'),null);assert.equal((await host.room()).version,room.version);});
test('answer remains server-only in all display/buzzer snapshots until reveal, even for room owner',async()=>{const room=await host.action('select',{cell:0});assert.ok(room.question.answer);for(const c of [host,observer,player1]){const snapshot=await c.room(c===player1?'buzzer':'display');const serialized=JSON.stringify(snapshot);assert.equal(snapshot.question.answer,undefined);assert.equal(snapshot.question.source,undefined);assert.equal(snapshot.current,undefined);assert.equal(snapshot.history,undefined);assert.equal(snapshot.used,undefined);assert.ok(!serialized.includes('password_hash'));}});
test('SSE publishes projected state, with no hidden answer in initial or subsequent events',async()=>{const controller=new AbortController();const response=await fetch(`${base}/api/rooms/${roomId}/events?view=display`,{headers:{Host:'127.0.0.1:39871',Cookie:`hk_sid=${observer.cookies.hk_sid}`},signal:controller.signal});assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/text\/event-stream/);const reader=response.body.getReader(),decoder=new TextDecoder();let text='';while(!text.includes('event: state')){text+=decoder.decode((await reader.read()).value);}const event=JSON.parse(text.match(/data: ({.*})/)[1]);assert.equal(event.question.answer,undefined);await host.action('buzz-open');let later='';while(!later.includes('event: state'))later+=decoder.decode((await reader.read()).value);assert.equal(JSON.parse(later.match(/data: ({.*})/)[1]).buzz.open,true);controller.abort();await reader.cancel().catch(()=>{});});
test('simultaneous buzzer requests choose exactly one winner and reject replay',async()=>{const room=await player1.room('buzzer'),payload={key:room.buzz.key,questionKey:room.questionKey};const results=await Promise.all([player1.request(`/rooms/${roomId}/buzz`,payload),player2.request(`/rooms/${roomId}/buzz`,payload)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const after=await host.room();assert.ok(after.buzz.winner);assert.equal(after.buzz.open,false);assert.ok(after.buzz.deadline>Date.now());assert.equal((await player1.request(`/rooms/${roomId}/buzz`,payload)).status,409);});
test('expired timer is handled from persisted deadline and auto-opens with a fresh buzzer generation',async()=>{const row=one('SELECT state FROM rooms WHERE id=?',roomId),state=JSON.parse(row.state),old=state.buzz.key;state.buzz.deadline=Date.now()-1;run('UPDATE rooms SET state=? WHERE id=?',JSON.stringify(state),roomId);expireBuzzers();const room=await host.room();assert.equal(room.buzz.open,true);assert.equal(room.buzz.winner,null);assert.notEqual(room.buzz.key,old);});
test('stale host moves are refused; answer reveal then award changes only one cell',async()=>{const before=await host.room();await host.action('reveal');assert.ok((await observer.room('display')).question.answer);assert.equal((await host.request(`/rooms/${roomId}/action`,{action:'award',version:before.version,team:1})).status,409);const room=await host.action('award',{team:1});assert.equal(room.board[0].owner,1);assert.equal(room.question,null);assert.equal(room.board.filter(c=>c.owner).length,1);});
test('complete connected win saves result; undo removes it; replay does not double-count; restart preserves completed match',async()=>{for(const cell of [4,8,12]){await host.action('select',{cell});await host.action('reveal');await host.action('award',{team:1});}let room=await host.room();assert.equal(room.winner,1);assert.deepEqual(room.path,[0,4,8,12]);assert.deepEqual((await player1.request('/profile')).data.stats,{games:1,wins:1});assert.deepEqual((await player2.request('/profile')).data.stats,{games:1,wins:0});await host.action('undo');assert.deepEqual((await player1.request('/profile')).data.stats,{games:0,wins:0});room=await host.room();assert.ok(room.question);assert.ok(room.revealed);await host.action('award',{team:1});assert.equal((await player1.request('/profile')).data.stats.games,1);await host.action('restart');room=await host.room();assert.equal(room.round,2);assert.ok(room.board.every(c=>!c.owner));assert.equal((await player1.request('/profile')).data.stats.games,1);});
test('question changes never reuse previously used question IDs and persisted state survives server recreation',async()=>{const room=await host.room();const cell=room.board.find(c=>one("SELECT count(*) AS n FROM questions WHERE letter=? AND status='published'",c.letter).n>10).index;await host.action('select',{cell});let internal=JSON.parse(one('SELECT state FROM rooms WHERE id=?',roomId).state);const first=internal.current.id;await host.action('change');internal=JSON.parse(one('SELECT state FROM rooms WHERE id=?',roomId).state);assert.notEqual(internal.current.id,first);const expected=await host.room();server.closeAllConnections();await new Promise(r=>server.close(r));await start();const after=await host.room();assert.deepEqual(after.board,expected.board);assert.equal(after.question.text,expected.question.text);assert.equal(after.version,expected.version);});
test('automatic mode hides the answer from its controller until reveal and still enforces owner authority',async()=>{const original=roomId,tournaments=(await host.request('/tournaments')).data;const result=await host.request('/rooms',{teams:[{name:'أخضر',color:'#15803d'},{name:'أزرق',color:'#2563eb'}],size:5,mode:'auto',seconds:10,tournaments:tournaments.map(t=>t.id),difficulty:'all'});assert.equal(result.status,201);roomId=result.data.id;const selected=await host.action('select',{cell:0});assert.equal(selected.question.answer,undefined);assert.equal(selected.buzz.open,true);assert.equal((await player1.request(`/rooms/${roomId}/action`,{action:'reveal',version:selected.version})).status,403);await host.action('reveal');assert.ok((await host.room()).question.answer);await host.action('award',{team:2});assert.equal((await host.room()).board[0].owner,2);roomId=original;});
test('kicked player cannot buzz or rejoin with the same session',async()=>{await host.action('kick',{userId:player2.user.id});assert.equal((await player2.request(`/rooms/${roomId}/join`,{team:2})).status,403);assert.equal((await player2.request(`/rooms/${roomId}?view=buzzer`)).status,403);});
test('two rounds resolve a sweep, a split adds a decider, and a new match keeps past results',async()=>{
  const oldRoom=roomId,config={teams:[{name:'الصقور',color:'#15803d'},{name:'النجوم',color:'#2563eb'}],size:4,rounds:2,mode:'human',seconds:10,tournaments:['saudi'],difficulty:'easy'};
  assert.equal((await host.request('/rooms',{...config,rounds:7})).status,422);
  const created=await host.request('/rooms',config);assert.equal(created.status,201,JSON.stringify(created.data));roomId=created.data.id;
  try{
    let board=await host.room();assert.equal(board.config.rounds,2);const available=one("SELECT count(DISTINCT letter) n FROM questions WHERE tournament_id='saudi' AND status='published'").n;assert.equal(new Set(board.board.map(c=>c.letter)).size,available);assert.equal(new Set(board.board.slice(0,available).map(c=>c.letter)).size,available);
    for(const cell of [0,4,8,12])board=await host.action('correct',{cell,team:1});
    assert.equal(board.winner,1);assert.deepEqual(board.results,[{round:1,winner:1}]);assert.equal(board.matchWinner,0);
    board=await host.action('restart');assert.equal(board.round,2);assert.equal(board.winner,0);
    for(const cell of [0,1,2,3])board=await host.action('correct',{cell,team:2});
    assert.equal(board.winner,2);assert.equal(board.matchWinner,0);assert.equal(board.results.length,2);
    board=await host.action('restart');assert.equal(board.round,3);
    for(const cell of [0,4,8,12])board=await host.action('correct',{cell,team:1});
    assert.equal(board.matchWinner,1);assert.equal((await host.request(`/rooms/${roomId}/action`,{action:'restart',version:board.version})).status,409);
    assert.equal(one('SELECT count(*) n FROM matches WHERE room_id=?',roomId).n,3);
    board=await host.action('new-match');assert.equal(board.round,1);assert.deepEqual(board.results,[]);assert.equal(board.matchWinner,0);
    assert.equal(one('SELECT count(*) n FROM matches WHERE room_id=?',roomId).n,3);
    for(const cell of [0,4,8,12])board=await host.action('correct',{cell,team:1});
    assert.equal(board.matchWinner,0);
    board=await host.action('restart');assert.equal(board.round,2);
    for(const cell of [0,4,8,12])board=await host.action('correct',{cell,team:1});
    assert.equal(board.matchWinner,1);assert.equal(board.round,2);
    assert.equal(one('SELECT count(*) n FROM matches WHERE room_id=?',roomId).n,5);
  }finally{roomId=oldRoom;}
});
test('admin login requires password + one-time TOTP; secrets are encrypted; guest sessions cannot access admin',async()=>{assert.equal((await host.request('/admin/questions')).status,401);for(const [username,role] of [['owner','owner'],['editor','questions']]){const secret=base32(randomBytes(20)),id=token(18),encrypted=sealSecret(secret);assert.notEqual(secret,encrypted);assert.equal(openSecret(encrypted),secret);run('INSERT INTO admins(id,username,password_hash,totp_secret,role,created_at) VALUES(?,?,?,?,?,?)',id,username,await passwordHash('Strong-test-password-123!'),encrypted,role,Date.now());const c=await new Client().init();const wrong=await c.request('/admin/login',{username,password:'Strong-test-password-123!',code:'000000'});assert.equal(wrong.status,401);const correct=await c.request('/admin/login',{username,password:'Strong-test-password-123!',code:totp(secret)});assert.equal(correct.status,200,JSON.stringify(correct.data));assert.equal(correct.data.admin.role,role);assert.equal((await c.request('/admin/login',{username,password:'Strong-test-password-123!',code:totp(secret)})).status,401);if(role==='owner')ownerAdmin=c;else editorAdmin=c;}assert.equal((await editorAdmin.request('/admin/settings')).status,403);assert.equal((await editorAdmin.request('/admin/rooms')).status,403);assert.equal((await editorAdmin.request('/admin/questions')).status,200);});
test('admin views, bounded import, unique question check, Arabic letter validation and SQL injection handling',async()=>{for(const route of ['overview','questions','mini-games','tournaments','rooms','mini-rooms','users','audit','settings','admins'])assert.equal((await ownerAdmin.request('/admin/'+route)).status,200,route);assert.equal((await ownerAdmin.request('/admin/questions?search=%27%20OR%201%3D1--')).status,200);const q={tournament_id:'saudi',letter:'ه',text:'سؤال اختبار إداري عن الهلال فقط؟',answer:'الهلال',difficulty:'easy',status:'hidden',source:'https://www.spl.com.sa/',note:''};assert.equal((await editorAdmin.request('/admin/question',{...q,letter:'ب'})).status,422);const before=one('SELECT count(*) AS n FROM questions').n;assert.equal((await editorAdmin.request('/admin/import',{questions:[q,q]})).status,409);assert.equal(one('SELECT count(*) AS n FROM questions').n,before);const saved=await editorAdmin.request('/admin/question',q);assert.equal(saved.status,200);assert.equal((await editorAdmin.request('/admin/question-delete',{id:saved.data.id})).status,200);const mini=one('SELECT * FROM mini_game_rounds LIMIT 1');const edited=await editorAdmin.request('/admin/mini-game-round',{id:mini.id,prompt:'سؤال إداري واضح لاختبار الجولة؟',solution:mini.solution,explanation:'شرح واضح للحل.',difficulty:mini.difficulty,status:'hidden',source:mini.source});assert.equal(edited.status,200,JSON.stringify(edited.data));assert.equal(one('SELECT status FROM mini_game_rounds WHERE id=?',mini.id).status,'hidden');});
test('only the owner can set a safe external support link, and clearing it hides it',async()=>{
    const current=(await ownerAdmin.request('/admin/settings')).data;
    const settings={maintenance:false,default_theme:'dark',max_players:Number(current.max_players),support_url:'https://example.org/support'};
    assert.equal((await editorAdmin.request('/admin/settings',settings)).status,403);
    for(const unsafe of ['javascript:alert(1)','http://example.org','https://owner:secret@example.org'])
        assert.equal((await ownerAdmin.request('/admin/settings',{...settings,support_url:unsafe})).status,422);
    assert.equal((await ownerAdmin.request('/admin/settings',settings)).status,200);
    assert.equal((await observer.request('/session')).data.supportUrl,settings.support_url);
    assert.equal((await ownerAdmin.request('/admin/settings',{...settings,support_url:''})).status,200);
    assert.equal((await observer.request('/session')).data.supportUrl,null);
});
test('rate limit prevents buzzer spam; security headers and no source/database disclosure',async()=>{run('DELETE FROM rates');const results=await Promise.all(Array.from({length:9},()=>player1.request(`/rooms/${roomId}/buzz`,{key:'fake',questionKey:'fake'})));assert.ok(results.some(r=>r.status===429));for(const path of ['/data/huroof.sqlite','/server/security.mjs','/.env','/seed/questions.json']){const r=await fetch(base+path,{headers:{Host:'127.0.0.1:39871'}});assert.equal(r.status,404,path);assert.ok(!(await r.text()).includes('password_hash'));}const r=await host.request('/session');assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal(r.headers.get('x-frame-options'),'DENY');});
test('live SQLite backup and restore pass integrity, preserve results and revoke old sessions',async()=>{const backupRoot=resolve(directory,'backups');await exec(process.execPath,['scripts/backup.mjs'],{env:{...process.env,BACKUP_DIR:backupRoot}});const {readdirSync}=await import('node:fs');const backupPath=resolve(backupRoot,readdirSync(backupRoot)[0]),restore=resolve(directory,'restored');await exec(process.execPath,['scripts/restore.mjs',backupPath,restore,'--server-stopped']);const {DatabaseSync}=await import('node:sqlite');const restored=new DatabaseSync(resolve(restore,'huroof.sqlite'),{readOnly:true});assert.equal(restored.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(restored.prepare('SELECT count(*) AS n FROM matches').get().n,one('SELECT count(*) AS n FROM matches').n);assert.equal(restored.prepare('SELECT count(*) AS n FROM sessions').get().n,0);assert.ok(existsSync(resolve(restore,'.session-key')));restored.close();});
test('production cookies are Secure and HSTS is present when HTTPS origin is configured',async()=>{process.env.NODE_ENV='production';const production=createApplication({origin:'https://game.example.com'});await new Promise(r=>production.server.listen(0,'127.0.0.1',r));const {get}=await import('node:http');const headers=await new Promise((resolve,reject)=>get({hostname:'127.0.0.1',port:production.server.address().port,path:'/api/session',headers:{Host:'game.example.com'}},res=>{res.resume();res.on('end',()=>resolve(res.headers));}).on('error',reject));assert.match(headers['set-cookie'].join(';'),/; Secure/);assert.match(headers['strict-transport-security'],/max-age=31536000/);production.server.closeAllConnections();await new Promise(r=>production.server.close(r));process.env.NODE_ENV='test';});

// Desktop-only health token is a local-process handshake, not an authentication secret for players.
test('desktop health endpoint refuses requests without the per-launch handshake token',async()=>{
  process.env.HK_DESKTOP_HEALTH_TOKEN='tests-only-health-token';
  try {
    const denied=await fetch(base+'/api/health');
    assert.equal(denied.status,403);
    const accepted=await fetch(base+'/api/health',{headers:{'X-Desktop-Health':'tests-only-health-token'}});
    assert.equal(accepted.status,200);
    assert.equal((await accepted.json()).ok,true);
  } finally { delete process.env.HK_DESKTOP_HEALTH_TOKEN; }
});
