import importlib.util,unittest
from pathlib import Path
class UefaSquadTest(unittest.TestCase):
 def test_list_b_and_keeper_stats_keep_dash_as_unavailable(self):
  p=Path(__file__).resolve().parents[1]/'scripts/acquire_uefa.py';self.assertTrue(p.exists(),'UEFA collector not implemented');s=importlib.util.spec_from_file_location('uefa',p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
  html='<h1>Club FC Squad UEFA Champions League 2026/27</h1><h2 class="squadlist--role">Goalkeepers</h2><pk-table class="table--squadlist"><pk-table-body><pk-table-row><pk-table-cell column-key="name"><span itemprop="numberedPosition">41</span><a title="Goal Keeper" href="/uefachampionsleague/clubs/players/123--goal-keeper/"><span slot="primary">Goal Keeper *</span><pk-avatar src="https://img.uefa.com/imgml/TP/players/1/2027/324x324/123.jpg"></pk-avatar></a></pk-table-cell><pk-table-cell column-key="nationality">GRE</pk-table-cell><pk-table-cell column-key="age">21</pk-table-cell><pk-table-cell column-key="matches">-</pk-table-cell><pk-table-cell column-key="goals">2</pk-table-cell></pk-table-row></pk-table-body></pk-table><h2 class="squadlist--role">Coach</h2><pk-table class="table--squadlist table--coach"><pk-table-body><pk-table-row><pk-table-cell column-key="coach"><span itemprop="name">Coach</span><div slot="secondary">SRB</div><pk-avatar src="https://img.uefa.com/imgml/TP/players/1/2027/324x324/456.jpg"></pk-avatar></pk-table-cell></pk-table-row></pk-table-body></pk-table>'
  result=m.squad(html,{'sourceClubId':'99','nameAsPublished':'Club FC'});p=result['players'][0];self.assertTrue(p['listBAsMarked']);self.assertIsNone(p['statistics']['appearances']);self.assertEqual(p['statistics']['goalsConceded'],2);self.assertIsNone(p['statistics']['goals']);self.assertIsNone(p['dateOfBirth']);self.assertEqual(result['coaches'][0]['sourcePersonId'],'456')
  encoded=html.replace('123--goal-keeper/','123--maurits-kj%C3%A6rgaard/')
  self.assertEqual(m.squad(encoded,{'sourceClubId':'99','nameAsPublished':'Club FC'})['players'][0]['sourcePersonId'],'123')
  with self.assertRaises(ValueError):m.squad(html,{'sourceClubId':'100','nameAsPublished':'Other FC'})
