import { env } from 'cloudflare:workers';
import { checkColors, findPath, makeBoard, publicQuestion } from '@/server/game.mjs';
import { miniMedia } from '@/server/mini-media.mjs';
import { normalizeSupportUrl } from '@/server/support-url.mjs';
import { MINI_CONTENT_VERSION, MINI_GAMES, MINI_MEDIA, MINI_ROUNDS, projectMiniRound } from '@/server/mini-content.mjs';

export const runtime = 'edge';
type Row = Record<string, any>;
const db = () => env.DB as D1Database;
const one = async (sql:string,...values:any[]):Promise<Row> => (await db().prepare(sql).bind(...values).first()) as Row;
const all = async (sql:string,...values:any[]):Promise<Row[]> => (await db().prepare(sql).bind(...values).all()).results as Row[];
const run = async (sql:string,...values:any[]) => db().prepare(sql).bind(...values).run();
const fail=(status:number,error:string):never=>{throw Object.assign(new Error(error),{status});};
const token=(n=32)=>btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(n)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const digest=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const now=()=>Date.now();
const BANK_VERSION=4;
const cookie=(r:Request,key:string)=>r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(key+'='))?.slice(key.length+1)||'';
const json=(data:any,status=200,cookies:string[]=[]):Response=>{const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY','cross-origin-resource-policy':'same-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','strict-transport-security':'max-age=31536000; includeSubDomains'});for(const c of cookies)h.append('set-cookie',c);return new Response(JSON.stringify(data),{status,headers:h});};
const setCookie=(key:string,value:string,age:number)=>`${key}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${age}`;
async function ensureMiniSchema(){
  // Keep long-lived D1 databases compatible even when a preview or deployment starts
  // before the migration runner has observed the newest migration journal entry.
  await run("CREATE TABLE IF NOT EXISTS football_entities(id TEXT PRIMARY KEY,entity_type TEXT NOT NULL,name_ar TEXT NOT NULL,name_en TEXT NOT NULL DEFAULT '',image_key TEXT NOT NULL DEFAULT '',image_source TEXT NOT NULL DEFAULT '',image_license TEXT NOT NULL DEFAULT '',fallback TEXT NOT NULL DEFAULT '',metadata TEXT NOT NULL DEFAULT '{}',updated_at INTEGER NOT NULL)");
  await run('CREATE INDEX IF NOT EXISTS idx_football_entities_type ON football_entities(entity_type)');
  await run("CREATE TABLE IF NOT EXISTS mini_game_rounds(id TEXT PRIMARY KEY,game_slug TEXT NOT NULL,difficulty TEXT NOT NULL,prompt TEXT NOT NULL,solution TEXT NOT NULL,accepted TEXT NOT NULL DEFAULT '[]',explanation TEXT NOT NULL DEFAULT '',visual_data TEXT NOT NULL DEFAULT '{}',source TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'published',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");
  await run('CREATE INDEX IF NOT EXISTS idx_mini_game_rounds_pool ON mini_game_rounds(game_slug,status,difficulty)');
  await run("CREATE TABLE IF NOT EXISTS mini_game_rooms(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES users(id),config TEXT NOT NULL,state TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,expires_at INTEGER NOT NULL)");
  await run('CREATE INDEX IF NOT EXISTS idx_mini_game_rooms_owner ON mini_game_rooms(owner_id,status)');
  await run('CREATE TABLE IF NOT EXISTS mini_game_members(room_id TEXT NOT NULL REFERENCES mini_game_rooms(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,team INTEGER NOT NULL,name TEXT NOT NULL,kicked INTEGER NOT NULL DEFAULT 0,joined_at INTEGER NOT NULL,last_seen INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(room_id,user_id))');
  await run('CREATE INDEX IF NOT EXISTS idx_mini_game_members_seen ON mini_game_members(room_id,last_seen)');
  await run('CREATE TABLE IF NOT EXISTS mini_game_events(id INTEGER PRIMARY KEY AUTOINCREMENT,room_id TEXT NOT NULL REFERENCES mini_game_rooms(id) ON DELETE CASCADE,message TEXT NOT NULL,created_at INTEGER NOT NULL)');
  await run('CREATE INDEX IF NOT EXISTS idx_mini_game_events_room ON mini_game_events(room_id,id)');
  const columns=new Set((await all('PRAGMA table_info(mini_game_rounds)')).map(column=>column.name));
  if(!columns.has('accepted'))await run("ALTER TABLE mini_game_rounds ADD COLUMN accepted TEXT NOT NULL DEFAULT '[]'");
  if(!columns.has('explanation'))await run("ALTER TABLE mini_game_rounds ADD COLUMN explanation TEXT NOT NULL DEFAULT ''");
  if(!columns.has('visual_data'))await run("ALTER TABLE mini_game_rounds ADD COLUMN visual_data TEXT NOT NULL DEFAULT '{}'");
}
async function seed(previewRepair=false){
  const current=Number((await one("SELECT value FROM settings WHERE key='seed_version'"))?.value||0);
  if(current<BANK_VERSION){
    // The 6000+ question payload is only needed by an unseeded database.
    const list=(await import('@/seed/questions.json')).default as {version:number,tournaments:Row[],questions:Row[]};
    if(current<4)await run("DELETE FROM questions WHERE note='قاعدة كروية عامة تنطبق على مباريات هذه البطولة.'");
    if(!current)await db().batch(list.tournaments.map(t=>db().prepare('INSERT OR IGNORE INTO tournaments(id,name,active,position) VALUES(?,?,1,?)').bind(t.id,t.name,t.position)));
    const pending=list.questions.filter(q=>!current||Number(q.pack||1)>current),chunks:Row[][]=[];for(let i=0;i<pending.length;i+=80)chunks.push(pending.slice(i,i+80));
    for(let i=0;i<chunks.length;i+=4)await Promise.all(chunks.slice(i,i+4).map(chunk=>db().batch(chunk.map(q=>db().prepare("INSERT OR IGNORE INTO questions(id,tournament_id,letter,text,answer,difficulty,status,source,note,created_at,updated_at) VALUES(?,?,?,?,?,?,'published',?,?,?,?)").bind(q.id,q.tournament_id,q.letter,q.text,q.answer,q.difficulty,q.source,q.note||'',now(),now())))));
    await db().batch([['maintenance','false'],['default_theme','dark'],['max_players','64']].map(([k,v])=>db().prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').bind(k,v)));
    await run("UPDATE settings SET value='dark' WHERE key='default_theme' AND value='auto'");await run("UPDATE users SET theme='dark' WHERE theme='auto'");await run("INSERT INTO settings(key,value) VALUES('seed_version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",String(list.version));
  }
  if(previewRepair)await ensureMiniSchema();
  const miniCurrent=Number((await one("SELECT value FROM settings WHERE key='mini_seed_version'"))?.value||0);
  if(miniCurrent<MINI_CONTENT_VERSION){
    await run("UPDATE mini_game_rounds SET status='hidden',updated_at=? WHERE id='gt-argentina'",now());
    for(let i=0;i<MINI_ROUNDS.length;i+=40)await db().batch(MINI_ROUNDS.slice(i,i+40).map(round=>db().prepare("INSERT INTO mini_game_rounds(id,game_slug,difficulty,prompt,solution,accepted,explanation,visual_data,source,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET game_slug=excluded.game_slug,difficulty=excluded.difficulty,prompt=excluded.prompt,solution=excluded.solution,accepted=excluded.accepted,explanation=excluded.explanation,visual_data=excluded.visual_data,source=excluded.source,updated_at=excluded.updated_at").bind(round.id,round.game_slug,round.difficulty,round.prompt,round.solution,JSON.stringify(round.accepted),round.explanation,JSON.stringify(round.visual),round.source,round.status,now(),now())));
    const media=Object.entries(MINI_MEDIA);for(let i=0;i<media.length;i+=40)await db().batch(media.slice(i,i+40).map(([id,item])=>db().prepare("INSERT INTO football_entities(id,entity_type,name_ar,name_en,image_key,image_source,image_license,fallback,metadata,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET entity_type=excluded.entity_type,image_key=excluded.image_key,image_source=excluded.image_source,image_license=excluded.image_license,fallback=excluded.fallback,updated_at=excluded.updated_at").bind(id,item.type,item.fallback,item.fallback,item.url,item.source,item.license,item.fallback,'{}',now())));
    await run("INSERT INTO settings(key,value) VALUES('mini_seed_version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",String(MINI_CONTENT_VERSION));
  }
}
// Each Worker isolate needs to check the seed once, not on every API request.
let seedPromise:Promise<void>|null=null;
function ensureSeed(previewRepair=false){if(!seedPromise)seedPromise=seed(previewRepair).catch(e=>{seedPromise=null;throw e;});return seedPromise;}
let lastCleanup=0;
async function cleanup(){const t=now();if(t-lastCleanup<30000)return;lastCleanup=t;const oldRooms=await all('SELECT id FROM rooms WHERE expires_at<?',t),oldMini=await all('SELECT id FROM mini_game_rooms WHERE expires_at<?',t),statements:D1PreparedStatement[]=[db().prepare('DELETE FROM sessions WHERE expires_at<?').bind(t),db().prepare('DELETE FROM challenges WHERE expires_at<?').bind(t),db().prepare('DELETE FROM rates WHERE reset_at<?').bind(t),db().prepare('DELETE FROM events WHERE created_at<?').bind(t-2592000000),db().prepare('DELETE FROM mini_game_events WHERE created_at<?').bind(t-2592000000),db().prepare('DELETE FROM audit WHERE created_at<?').bind(t-7776000000)];for(const {id} of oldRooms)statements.push(db().prepare('DELETE FROM match_players WHERE match_id IN (SELECT id FROM matches WHERE room_id=?)').bind(id),db().prepare('DELETE FROM matches WHERE room_id=?').bind(id),db().prepare('DELETE FROM events WHERE room_id=?').bind(id),db().prepare('DELETE FROM members WHERE room_id=?').bind(id),db().prepare('DELETE FROM rooms WHERE id=?').bind(id));for(const {id} of oldMini)statements.push(db().prepare('DELETE FROM mini_game_events WHERE room_id=?').bind(id),db().prepare('DELETE FROM mini_game_members WHERE room_id=?').bind(id),db().prepare('DELETE FROM mini_game_rooms WHERE id=?').bind(id));for(let i=0;i<statements.length;i+=80)await db().batch(statements.slice(i,i+80));}
async function limit(key:string,max:number,ms:number,amount=1){const hashed=await digest(key),t=now();const result=await one('INSERT INTO rates(key,count,reset_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset_at<? THEN excluded.count ELSE count+excluded.count END,reset_at=CASE WHEN reset_at<? THEN excluded.reset_at ELSE reset_at END RETURNING count',hashed,amount,t+ms,t,t);if(result.count>max)fail(429,'طلبات كثيرة. انتظر قليلًا ثم حاول مرة أخرى.');}
// Reserve a short-lived poll allowance in D1 instead of writing to D1 on every screen refresh.
const pollAllowances=new Map<string,{left:number,expires:number}>();
async function limitPoll(key:string,max:number){const t=now(),allowance=pollAllowances.get(key);if(allowance&&allowance.expires>t&&allowance.left>0){allowance.left--;return;}await limit('room-poll:'+key,max,60000,50);if(pollAllowances.size>8192)pollAllowances.clear();pollAllowances.set(key,{left:49,expires:t+5000});}
async function sessionContext(r:Request):Promise<{session:Row|null,user:Row|null}>{const raw=cookie(r,'hk_sid');if(!/^[A-Za-z0-9_-]{43}$/.test(raw))return {session:null,user:null};const row=await one("SELECT s.*,u.id joined_user_id,u.name joined_user_name,u.theme joined_user_theme,u.blocked joined_user_blocked FROM sessions s LEFT JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.kind='guest' AND s.expires_at>?",await digest(raw),now());if(!row)return {session:null,user:null};const user=row.joined_user_id&&!row.joined_user_blocked?{id:row.joined_user_id,name:row.joined_user_name,theme:row.joined_user_theme}:null;return {session:row,user};}
// Settings can change in the admin panel; keep the cache short and invalidate on writes.
let settingsCache:Record<string,string>|null=null,settingsExpires=0;
async function settings():Promise<Record<string,string>>{if(settingsCache&&now()<settingsExpires)return settingsCache;const values=await all('SELECT key,value FROM settings');const latest:Record<string,string>=Object.fromEntries(values.map(x=>[x.key,x.value]));settingsCache=latest;settingsExpires=now()+5000;return latest;}
async function setting(k:string,f=''){return (await settings())[k]||f;}
let tournamentsCache:Row[]|null=null,tournamentsExpires=0;
async function publicTournaments(){if(tournamentsCache&&now()<tournamentsExpires)return tournamentsCache;tournamentsCache=await all("SELECT t.id,t.name,t.position,count(q.id) questions FROM tournaments t LEFT JOIN questions q ON q.tournament_id=t.id AND q.status='published' WHERE t.active=1 GROUP BY t.id ORDER BY t.position");tournamentsExpires=now()+60000;return tournamentsCache;}
async function payload(s:Row,admin:Row|null,u:Row|null){const options=await settings();return {user:u?{id:u.id,name:u.name,theme:u.theme}:null,admin,csrf:s.csrf,bot:{provider:'captcha'},defaultTheme:options.default_theme||'dark',maintenance:options.maintenance==='true',supportUrl:normalizeSupportUrl(options.support_url)||null};}
async function body(r:Request,max=8192):Promise<Row>{if(!r.headers.get('content-type')?.startsWith('application/json'))fail(415,'نوع الطلب غير صحيح.');if(Number(r.headers.get('content-length')||0)>max)fail(413,'الطلب كبير جدًا.');const reader=r.body?.getReader();if(!reader)return fail(400,'بيانات الطلب غير صحيحة.');const chunks:Uint8Array[]= [];let size=0;for(;;){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();fail(413,'الطلب كبير جدًا.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}let data;try{data=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{fail(400,'بيانات الطلب غير صحيحة.');}if(!data||typeof data!=='object'||Array.isArray(data))fail(400,'بيانات الطلب غير صحيحة.');return data;}
function validName(v:any){const n=String(v||'').normalize('NFKC').trim();if(n.length<2||n.length>24||/[\p{Cc}\p{Cf}<>]/u.test(n))fail(422,'اكتب اسمًا من حرفين إلى ٢٤ حرفًا.');return n;}
function questionFilter(config:Row,letter?:string){const ids=config.tournaments,values:any[]=[...ids];let sql=`q.status='published' AND t.active=1 AND q.tournament_id IN (${ids.map(()=>'?').join(',')})`;if(config.difficulty!=='all'){sql+=' AND q.difficulty=?';values.push(config.difficulty);}if(letter){sql+=' AND q.letter=?';values.push(letter);}return {sql,values};}
async function questionCoverage(config:Row){const collect=async(candidate:Row)=>{const filter=questionFilter(candidate),rows=await all(`SELECT q.letter,count(*) count FROM questions q JOIN tournaments t ON t.id=q.tournament_id WHERE ${filter.sql} GROUP BY q.letter`,...filter.values),coverage:Record<string,number>={};for(const row of rows)coverage[row.letter]=Number(row.count);return coverage;},preferred=await collect(config);return Object.values(preferred).reduce((sum,count)=>sum+count,0)>=config.size*config.size||config.difficulty==='all'?preferred:collect({...config,difficulty:'all'});}
async function pickQuestion(config:Row,letter:string,used:string[]){const pick=async(candidate:Row)=>{const filter=questionFilter(candidate,letter);return one(`SELECT q.*,t.name tournament FROM questions q JOIN tournaments t ON t.id=q.tournament_id WHERE ${filter.sql} AND q.id NOT IN (SELECT value FROM json_each(?)) ORDER BY random() LIMIT 1`,...filter.values,JSON.stringify(used));};return await pick(config)||(config.difficulty!=='all'?pick({...config,difficulty:'all'}):null);}
async function fresh(config:Row,round=1,results:Row[]=[],matchKey=round){return {round,matchKey,results,matchWinner:0,board:makeBoard(config.size,await questionCoverage(config)),current:null as Row|null,cell:null as number|null,revealed:false,used:[] as string[],history:[] as Row[],winner:0,path:[] as number[],buzz:closedBuzz(),questionKey:token(12)};}
function closedBuzz(){return {open:false,winner:null as Row|null,deadline:null as number|null,key:token(12)};}
async function getRoom(id:string){const row=await one('SELECT * FROM rooms WHERE id=?',id);if(!row)fail(404,'الغرفة غير موجودة.');if(row.status!=='open'||row.expires_at<now())fail(410,'انتهت هذه الغرفة.');if(row.expires_at<now()+8*60*1000){row.expires_at=now()+10*60*1000;await run('UPDATE rooms SET expires_at=? WHERE id=?',row.expires_at,id);}return {...row,config:JSON.parse(row.config),state:JSON.parse(row.state)};}
async function members(id:string){return all('SELECT user_id id,name,team,last_seen FROM members WHERE room_id=? AND kicked=0 ORDER BY joined_at',id);}
async function member(room:Row,u:Row|null):Promise<Row>{if(!u)fail(401,'ادخل باسمك أولًا.');const m=await one('SELECT * FROM members WHERE room_id=? AND user_id=?',room.id,u!.id);if(!m||m.kicked)fail(403,'لست ضمن لاعبي الغرفة.');return m;}
function owner(room:Row,u:Row|null){if(!u||u.id!==room.owner_id)fail(403,'التحكم للمقدم فقط.');}
async function project(room:Row,view:string,u:Row|null,authorized=false){if(view==='host')owner(room,u);if(view==='buzzer'&&!authorized)await member(room,u);const [players,events]=await Promise.all([members(room.id),view==='host'?all('SELECT id,message,created_at FROM events WHERE room_id=? ORDER BY id DESC LIMIT 40',room.id):Promise.resolve([])]),s=room.state,controller=u?.id===room.owner_id;return {id:room.id,version:room.version,config:room.config,serverTime:now(),round:s.round,results:s.results||[],matchWinner:s.matchWinner||0,board:s.board,cell:s.cell,question:publicQuestion(s.current,s.revealed||(view==='host'&&room.config.mode==='human')),revealed:s.revealed,winner:s.winner,path:s.path,buzz:s.buzz,questionKey:s.questionKey,playersCount:players.length,canControl:room.config.mode==='auto'&&controller,me:u?players.find(p=>p.id===u.id)||null:null,...(view==='host'?{players:players.map(p=>({id:p.id,name:p.name,team:p.team,online:p.last_seen>now()-30000})),events,canUndo:s.history.length>0,links:{display:`/room/${room.id}/display`,buzzer:`/room/${room.id}/buzzer`}}:{})};}
async function save(room:Row,message:string){const stamp=now(),statements=[db().prepare('UPDATE rooms SET state=?,version=version+1,updated_at=?,expires_at=? WHERE id=? AND version=?').bind(JSON.stringify(room.state),stamp,stamp+10*60*1000,room.id,room.version)];if(message)statements.push(db().prepare('INSERT INTO events(room_id,message,created_at) VALUES(?,?,?)').bind(room.id,message,stamp));const [result]=await db().batch(statements);if(result.meta.changes!==1)fail(409,'تغيرت المباراة، حاول مرة أخرى.');room.version++;}
function remember(s:Row){const copy=structuredClone(s);delete copy.history;s.history.push(copy);s.history=s.history.slice(-40);}
async function recordWinner(room:Row){const s=room.state;s.winner=0;s.path=[];for(const team of [1,2]){const path=findPath(s.board,room.config.size,team);if(path.length){s.winner=team;s.path=path;break;}}if(s.winner)s.buzz=closedBuzz();s.results=(s.results||[]).filter((result:Row)=>result.round!==s.round);if(s.winner)s.results.push({round:s.round,winner:s.winner});s.matchWinner=0;if(s.round>=(room.config.rounds||2)&&s.winner){const wins=[1,2].map(team=>s.results.filter((result:Row)=>result.winner===team).length);if(wins[0]!==wins[1])s.matchWinner=wins[0]>wins[1]?1:2;}}
async function updateMatch(room:Row){const s=room.state,key=s.matchKey||s.round;const statements=[db().prepare('DELETE FROM match_players WHERE match_id IN (SELECT id FROM matches WHERE room_id=? AND round=?)').bind(room.id,key),db().prepare('DELETE FROM matches WHERE room_id=? AND round=?').bind(room.id,key)];if(s.winner){const id=token(18);statements.push(db().prepare('INSERT INTO matches(id,room_id,round,winner,board,finished_at) VALUES(?,?,?,?,?,?)').bind(id,room.id,key,s.winner,JSON.stringify(s.board),now()));for(const p of await members(room.id))statements.push(db().prepare('INSERT INTO match_players(match_id,user_id,won) VALUES(?,?,?)').bind(id,p.id,Number(p.team===s.winner)));}await db().batch(statements);}
async function expire(room:Row){const s=room.state;if(!s.buzz.deadline||s.buzz.deadline>now())return room;s.buzz=closedBuzz();if(room.config.autoReopen&&s.current&&!s.revealed)s.buzz.open=true;await save(room,'انتهى وقت الإجابة');return room;}
async function configFrom(b:Row){const c={teams:[{name:validName(b.teams?.[0]?.name),color:String(b.teams?.[0]?.color||'')},{name:validName(b.teams?.[1]?.name),color:String(b.teams?.[1]?.color||'')}],size:b.size,rounds:b.rounds===undefined?2:b.rounds,mode:b.mode,seconds:b.seconds,tournaments:[...new Set(Array.isArray(b.tournaments)?b.tournaments:[])] as string[],difficulty:b.difficulty||'all',autoReopen:b.autoReopen===true};if(![4,5,6,7].includes(c.size)||![2,3,4,5,6].includes(c.rounds)||!['human','auto'].includes(c.mode)||![5,10,15,20].includes(c.seconds)||!['all','easy','medium','hard'].includes(c.difficulty)||!checkColors(c.teams[0].color,c.teams[1].color)||c.teams[0].name===c.teams[1].name)fail(422,'راجع إعدادات المباراة.');if(!c.tournaments.length||c.tournaments.length>50||c.tournaments.some(id=>typeof id!=='string'))fail(422,'اختر بطولة.');const placeholders=c.tournaments.map(()=>'?').join(','),available=Number((await one(`SELECT count(*) count FROM tournaments WHERE active=1 AND id IN (${placeholders})`,...c.tournaments))?.count||0);if(available!==c.tournaments.length)fail(422,'اختر بطولة متاحة.');return c;}

const MINI_TTL=10*60*1000,miniSlugs=new Set(MINI_GAMES.map(game=>game.slug));
function miniName(value:any){const name=String(value||'').normalize('NFKC').trim();if(name.length<1||name.length>24||/[\p{Cc}\p{Cf}<>]/u.test(name))fail(422,'اكتب اسم فريق واضحًا حتى ٢٤ حرفًا.');return name;}
function miniClosed(){return {open:false,winner:null as Row|null,deadline:null as number|null,key:token(12)};}
async function miniConfig(b:Row){let game=String(b.game||'');if(game==='random')game=MINI_GAMES[crypto.getRandomValues(new Uint32Array(1))[0]%MINI_GAMES.length].slug;if(game!=='party'&&!miniSlugs.has(game))fail(422,'اختر لعبة متاحة.');const c={game,teams:[{name:miniName(b.teams?.[0]?.name),color:String(b.teams?.[0]?.color||'')},{name:miniName(b.teams?.[1]?.name),color:String(b.teams?.[1]?.color||'')}],difficulty:String(b.difficulty||'all'),rounds:Number(b.rounds||2),seconds:Number(b.seconds||5)};if(c.teams[0].name===c.teams[1].name||!checkColors(c.teams[0].color,c.teams[1].color)||!['all','easy','medium','hard','mixed'].includes(c.difficulty)||![2,3,4,5,6,10].includes(c.rounds)||![5,10,15,20].includes(c.seconds))fail(422,'راجع إعدادات اللعبة.');return c;}
function miniRoundRow(row:Row|null){return row?{...row,accepted:JSON.parse(row.accepted||'[]'),visual:JSON.parse(row.visual_data||'{}')}:null;}
async function chooseMini(c:Row,used:string[]=[]){const where=["status='published'"],params:any[]=[];if(c.game!=='party'){where.push('game_slug=?');params.push(c.game);}if(c.difficulty!=='all'){where.push('difficulty=?');params.push(c.difficulty);}let row=await one(`SELECT * FROM mini_game_rounds WHERE ${where.join(' AND ')} AND id NOT IN (SELECT value FROM json_each(?)) ORDER BY random() LIMIT 1`,...params,JSON.stringify(used));if(!row&&c.difficulty!=='all'){const base=c.game==='party'?"status='published'":"status='published' AND game_slug=?";row=await one(`SELECT * FROM mini_game_rounds WHERE ${base} AND id NOT IN (SELECT value FROM json_each(?)) ORDER BY random() LIMIT 1`,...(c.game==='party'?[]:[c.game]),JSON.stringify(used));}if(!row){const base=c.game==='party'?"status='published'":"status='published' AND game_slug=?";row=await one(`SELECT * FROM mini_game_rounds WHERE ${base} ORDER BY random() LIMIT 1`,...(c.game==='party'?[]:[c.game]));}if(!row)fail(503,'محتوى اللعبة غير متاح الآن.');return miniRoundRow(row)!;}
async function miniFresh(c:Row,number=1,scores=[0,0],used:string[]=[]){const round=await chooseMini(c,used);return {number,scores,currentId:round.id,used:[...used,round.id],revealed:false,buzz:{...miniClosed(),open:true},roundKey:token(12),audioPlays:0,finished:false,winner:0};}
async function getMini(id:string,touch=true){const row=await one('SELECT * FROM mini_game_rooms WHERE id=?',id);if(!row)fail(404,'غرفة Mini Games غير موجودة.');if(row.status!=='open'||row.expires_at<now()){await db().batch([db().prepare('DELETE FROM mini_game_events WHERE room_id=?').bind(id),db().prepare('DELETE FROM mini_game_members WHERE room_id=?').bind(id),db().prepare('DELETE FROM mini_game_rooms WHERE id=?').bind(id)]);fail(410,'انتهت الغرفة لعدم النشاط.');}const room={...row,config:JSON.parse(row.config),state:JSON.parse(row.state)};if(room.state.buzz?.deadline&&room.state.buzz.deadline<=now()&&!room.state.revealed){room.state.buzz={...miniClosed(),open:true};await saveMini(room,'انتهى وقت الإجابة وفُتح الجرس من جديد');}if(touch&&room.expires_at<now()+8*60*1000){room.expires_at=now()+MINI_TTL;await run('UPDATE mini_game_rooms SET expires_at=? WHERE id=?',room.expires_at,id);}return room;}
function miniOwner(room:Row,u:Row|null){if(!u||u.id!==room.owner_id)fail(403,'التحكم للمقدم فقط.');}
async function miniMembers(id:string){return all('SELECT user_id id,name,team,last_seen FROM mini_game_members WHERE room_id=? AND kicked=0 ORDER BY joined_at',id);}
async function miniMember(room:Row,u:Row|null){if(!u)fail(401,'ادخل باسمك أولًا.');const m=await one('SELECT * FROM mini_game_members WHERE room_id=? AND user_id=?',room.id,u.id);if(!m||m.kicked)fail(403,'انضم إلى أحد الفريقين أولًا.');return m;}
async function miniCurrent(room:Row){return miniRoundRow(await one('SELECT * FROM mini_game_rounds WHERE id=?',room.state.currentId))!;}
async function miniProject(room:Row,view:string,u:Row|null,authorized=false){if(view==='host')miniOwner(room,u);if(view==='buzzer'&&!authorized)await miniMember(room,u);const [players,round,events]=await Promise.all([miniMembers(room.id),miniCurrent(room),view==='host'?all('SELECT id,message,created_at FROM mini_game_events WHERE room_id=? ORDER BY id DESC LIMIT 30',room.id):Promise.resolve([])]),s=room.state,projected=projectMiniRound(round,s.revealed);if(!projected)fail(409,'تغير محتوى الجولة. اختر سؤالًا جديدًا.');return {id:room.id,version:room.version,config:room.config,serverTime:now(),number:s.number,scores:s.scores,round:projected.round,revealed:s.revealed,buzz:s.buzz,roundKey:s.roundKey,audioPlays:s.audioPlays,finished:s.finished,winner:s.winner,playersCount:players.length,me:u?players.find(p=>p.id===u.id)||null:null,media:projected.media,...(view==='host'?{players:players.map(p=>({...p,online:p.last_seen>now()-30000})),events,links:{display:`/mini-room/${room.id}/display`,buzzer:`/mini-room/${room.id}/buzzer`}}:{})};}
async function saveMini(room:Row,message=''){const stamp=now(),result=await run('UPDATE mini_game_rooms SET state=?,config=?,version=version+1,updated_at=?,expires_at=? WHERE id=? AND version=?',JSON.stringify(room.state),JSON.stringify(room.config),stamp,stamp+MINI_TTL,room.id,room.version);if(result.meta.changes!==1)fail(409,'تغيرت الجولة، حاول مرة أخرى.');room.version++;if(message)await run('INSERT INTO mini_game_events(room_id,message,created_at) VALUES(?,?,?)',room.id,message,stamp);}
async function miniAction(room:Row,u:Row,b:Row){miniOwner(room,u);if(Number(b.version)!==room.version)fail(409,'تغيرت الجولة. انتظر التحديث.');const s=room.state;let message='';switch(b.action){case'reveal':if(s.finished||s.revealed)fail(409,'لا توجد إجابة جديدة للكشف.');s.revealed=true;s.buzz=miniClosed();message='ظهر الحل';break;case'audio':{const round=await miniCurrent(room);if(round.game_slug!=='iconic-commentary')fail(409,'هذه الجولة بلا وصف صوتي.');if(s.audioPlays>=2)fail(409,'استخدمت فرصتي تشغيل الوصف.');s.audioPlays++;message=`شُغّل الوصف الصوتي (${s.audioPlays}/2)`;break;}case'buzz-open':if(s.finished||s.revealed)fail(409,'الجرس غير متاح.');s.buzz={...miniClosed(),open:true};message='فُتح الجرس';break;case'buzz-close':s.buzz=miniClosed();message='أُغلق الجرس';break;case'change':{const next=await chooseMini(room.config,s.used);s.currentId=next.id;s.used.push(next.id);s.revealed=false;s.buzz={...miniClosed(),open:true};s.roundKey=token(12);s.audioPlays=0;message='تغير السؤال';break;}case'award':{if(!s.revealed)fail(409,'اكشف الحل أولًا.');const team=Number(b.team);if(![0,1,2].includes(team))fail(422,'الفريق غير صحيح.');if(team)s.scores[team-1]++;if(s.number>=room.config.rounds&&s.scores[0]!==s.scores[1]){s.finished=true;s.winner=s.scores[0]>s.scores[1]?1:2;s.buzz=miniClosed();message=`فاز ${room.config.teams[s.winner-1].name}`;}else{if(s.number>=room.config.rounds&&s.scores[0]===s.scores[1])room.config.rounds++;room.state=await miniFresh(room.config,s.number+1,s.scores,s.used);message=team?`نقطة لـ ${room.config.teams[team-1].name}`:'انتقلتم دون نقطة';}break;}case'new-match':room.state=await miniFresh(room.config);message='بدأت مباراة جديدة';break;case'kick':{const target=String(b.userId||'');if(!await one('SELECT user_id FROM mini_game_members WHERE room_id=? AND user_id=?',room.id,target))fail(404,'اللاعب غير موجود.');await run('UPDATE mini_game_members SET kicked=1 WHERE room_id=? AND user_id=?',room.id,target);if(s.buzz.winner?.id===target)s.buzz=miniClosed();message='أُزيل لاعب';break;}default:fail(422,'الإجراء غير معروف.');}await saveMini(room,message);return miniProject(room,'host',u);}
async function act(room:Row,u:Row,b:Row){owner(room,u);const s=room.state;if(b.version!==room.version)fail(409,'تغيّرت المباراة. انتظر التحديث.');let msg='',match=false;
  switch(b.action){
  case 'select':{const i=b.cell;if(s.winner||s.current||!Number.isInteger(i)||!s.board[i]||s.board[i].owner)fail(422,'اختر خلية متاحة.');const question=await pickQuestion(room.config,s.board[i].letter,s.used);if(!question)fail(422,'نفدت أسئلة الحرف.');remember(s);s.current=question;s.used.push(s.current.id);s.cell=i;s.revealed=false;s.questionKey=token(12);s.buzz=closedBuzz();s.buzz.open=room.config.mode==='auto';msg='اختير حرف '+s.current.letter;break;}
  case 'change':{if(!s.current)fail(409,'اختر حرفًا أولًا.');const question=await pickQuestion(room.config,s.current.letter,s.used);if(!question)fail(422,'لا يوجد سؤال بديل.');remember(s);s.current=question;s.used.push(s.current.id);s.revealed=false;s.questionKey=token(12);s.buzz=closedBuzz();s.buzz.open=room.config.mode==='auto';msg='تغيّر السؤال';break;}
  case 'reveal':if(!s.current)fail(409,'لا يوجد سؤال مفتوح.');s.revealed=true;s.buzz=closedBuzz();msg='ظهرت الإجابة';break;
  case 'award':{if(!s.current||!s.revealed||![0,1,2].includes(b.team))fail(409,'أظهر الإجابة وحدد الفريق.');remember(s);if(b.team)s.board[s.cell].owner=b.team;msg=b.team?'احتسبت الخلية لصالح '+room.config.teams[b.team-1].name:'انتهى السؤال دون نقطة';s.current=null;s.cell=null;s.revealed=false;s.buzz=closedBuzz();await recordWinner(room);match=true;break;}
  case 'buzz-open':if(!s.current||s.revealed||s.winner)fail(409,'الجرس غير متاح.');s.buzz=closedBuzz();s.buzz.open=true;msg='فُتح الجرس';break;
  case 'buzz-close':s.buzz=closedBuzz();msg='أُغلق الجرس';break;
  case 'correct':{if(s.current||!Number.isInteger(b.cell)||!s.board[b.cell]||![0,1,2].includes(b.team))fail(422,'الخلية أو الفريق غير صحيح.');remember(s);s.board[b.cell].owner=b.team;await recordWinner(room);match=true;msg='عُدلت خلية';break;}
  case 'undo':{if(!s.history.length)fail(409,'لا توجد حركة للتراجع.');const used=s.used,history=s.history,previous=history.pop();room.state={...previous,history,used:[...new Set([...previous.used,...used])],questionKey:token(12),buzz:closedBuzz()};await recordWinner(room);match=true;msg='تراجع المقدم';break;}
  case 'restart':if(!s.winner||s.matchWinner)fail(409,'أكمل الجولة أو ابدأ مباراة جديدة.');room.state=await fresh(room.config,s.round+1,s.results||[],(s.matchKey||s.round)+1);msg='بدأت الجولة التالية';break;
  case 'new-match':room.state=await fresh(room.config,1,[],(s.matchKey||s.round)+1);msg='بدأت مباراة جديدة';break;
  case 'kick':{const m=await one('SELECT user_id FROM members WHERE room_id=? AND user_id=?',room.id,String(b.userId||''));if(!m)fail(404,'اللاعب غير موجود.');await run('UPDATE members SET kicked=1 WHERE room_id=? AND user_id=?',room.id,b.userId);if(s.buzz.winner?.id===b.userId)s.buzz=closedBuzz();msg='أُزيل لاعب';break;}
  default:fail(422,'الإجراء غير معروف.');
  }
  await save(room,msg);if(match)await updateMatch(room);return project(room,'host',u);
}
function validSource(value:string){try{const u=new URL(value);return u.protocol==='https:'&&!!u.hostname&&!u.username&&!u.password&&!/\s/.test(value);}catch{return false;}}
function questionInput(b:Row){const q:Row={};for(const key of ['tournament_id','letter','text','answer','difficulty','status','source','note'])q[key]=String(b[key]||'').trim();if(q.text.length<12||q.text.length>600||q.answer.length<2||q.answer.length>180||q.note.length>800||!['easy','medium','hard'].includes(q.difficulty)||!['published','hidden'].includes(q.status)||!validSource(q.source)||q.source.length>1000)fail(422,'راجع السؤال والإجابة والمصدر.');const normalized=q.answer.normalize('NFKC').replace(/[\u064B-\u065F\u0670ـ]/g,'').replace(/[أإآٱ]/g,'ا').replace(/^ال/,'');if(normalized[0]!==q.letter||!('ابتثجحخدذرزسشصضطظعغفقكلمنهوي'.includes(q.letter)))fail(422,'حرف الإجابة غير صحيح.');return q;}
async function adminGet(name:string,url:URL){switch(name){
  case 'overview':{const [counts,competitions,popular]=await Promise.all([one("SELECT (SELECT count(*) FROM questions) questions,(SELECT count(*) FROM questions WHERE status='published') published,(SELECT count(*) FROM rooms WHERE status='open' AND expires_at>?) rooms,(SELECT count(*) FROM matches) matches,(SELECT count(*) FROM users) users",now()),all('SELECT t.id,t.name,count(q.id) questions FROM tournaments t LEFT JOIN questions q ON q.tournament_id=t.id GROUP BY t.id ORDER BY t.position'),all("SELECT t.name,count(*) rooms FROM rooms r,json_each(r.config,'$.tournaments') j JOIN tournaments t ON t.id=j.value GROUP BY t.id ORDER BY rooms DESC LIMIT 5")]);return {...counts,competitions,popular,role:'owner'};}
  case 'questions':{let predicates=['1=1'],params:any[]=[];for(const [key,col] of [['tournament','q.tournament_id'],['letter','q.letter'],['status','q.status'],['difficulty','q.difficulty']]){const val=url.searchParams.get(key);if(val&&val!=='all'){predicates.push(col+'=?');params.push(val);}}const search=url.searchParams.get('search')?.slice(0,100);if(search){predicates.push('(q.text LIKE ? OR q.answer LIKE ?)');params.push('%'+search+'%','%'+search+'%');}const where=predicates.join(' AND '),page=Math.max(1,Math.min(10000,Number(url.searchParams.get('page'))||1));return {items:await all(`SELECT q.*,t.name tournament FROM questions q JOIN tournaments t ON t.id=q.tournament_id WHERE ${where} ORDER BY q.updated_at DESC,q.id LIMIT 25 OFFSET ?`,...params,(page-1)*25),total:(await one(`SELECT count(*) n FROM questions q WHERE ${where}`,...params)).n,page};}
  case 'tournaments':return all('SELECT t.*,count(q.id) questions FROM tournaments t LEFT JOIN questions q ON q.tournament_id=t.id GROUP BY t.id ORDER BY t.position,t.name');
  case 'export':return all('SELECT tournament_id,letter,text,answer,difficulty,status,source,note FROM questions ORDER BY tournament_id,id');
  case 'rooms':return (await all('SELECT id,owner_id,config,status,created_at,expires_at FROM rooms ORDER BY created_at DESC LIMIT 200')).map(r=>({...r,config:JSON.parse(r.config)}));
  case 'mini-games':return (await all('SELECT id,game_slug,difficulty,prompt,solution,accepted,explanation,source,status,updated_at FROM mini_game_rounds ORDER BY game_slug,id')).map(r=>({...r,accepted:JSON.parse(r.accepted||'[]')}));
  case 'mini-rooms':return (await all('SELECT id,owner_id,config,state,status,created_at,expires_at FROM mini_game_rooms ORDER BY created_at DESC LIMIT 200')).map(r=>({...r,config:JSON.parse(r.config),state:JSON.parse(r.state)}));
  case 'users':return all('SELECT id,name,blocked,created_at FROM users ORDER BY created_at DESC LIMIT 200');
  case 'audit':return all('SELECT * FROM audit ORDER BY id DESC LIMIT 200');
  case 'settings':return {support_url:'',...Object.fromEntries((await all("SELECT key,value FROM settings WHERE key IN ('maintenance','default_theme','max_players','support_url')")).map(x=>[x.key,x.value]))};
  case 'admins':return [{id:'owner',username:'يزن',role:'owner',active:1,created_at:0}];
  default:fail(404,'القسم غير موجود.');
}}
async function adminWrite(name:string,b:Row){const audit=async(action:string,target='')=>run('INSERT INTO audit(actor,action,target,created_at) VALUES(?,?,?,?)','owner',action,target.slice(0,180),now());switch(name){
  case 'question':{const q=questionInput(b),t=await one('SELECT id FROM tournaments WHERE id=?',q.tournament_id);if(!t)fail(422,'اختر بطولة صحيحة.');const id=b.id||token(18);if(b.id&&!await one('SELECT id FROM questions WHERE id=?',id))fail(404,'السؤال غير موجود.');await run('INSERT INTO questions(id,tournament_id,letter,text,answer,difficulty,status,source,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET tournament_id=excluded.tournament_id,letter=excluded.letter,text=excluded.text,answer=excluded.answer,difficulty=excluded.difficulty,status=excluded.status,source=excluded.source,note=excluded.note,updated_at=excluded.updated_at',id,q.tournament_id,q.letter,q.text,q.answer,q.difficulty,q.status,q.source,q.note,now(),now());await audit(b.id?'question.update':'question.create',id);return {id};}
  case 'question-delete':await run('DELETE FROM questions WHERE id=?',String(b.id||''));await audit('question.delete',String(b.id||''));return {ok:true};
  case 'mini-game-round':{const id=String(b.id||''),prompt=String(b.prompt||'').trim(),solution=String(b.solution||'').trim(),explanation=String(b.explanation||'').trim(),source=String(b.source||'').trim(),difficulty=String(b.difficulty||''),status=String(b.status||''),accepted=(Array.isArray(b.accepted)?b.accepted:[solution]).map(value=>String(value).trim()).filter(Boolean);if(!await one('SELECT id FROM mini_game_rounds WHERE id=?',id))fail(404,'الجولة غير موجودة.');if(prompt.length<8||prompt.length>240||solution.length<1||solution.length>180||explanation.length>600||!accepted.length||accepted.length>50||accepted.some(value=>value.length>180)||!['easy','medium','hard','mixed'].includes(difficulty)||!['published','hidden'].includes(status)||!validSource(source))fail(422,'راجع نص الجولة والحل والإجابات المقبولة والمصدر والحالة.');await run('UPDATE mini_game_rounds SET prompt=?,solution=?,accepted=?,explanation=?,source=?,difficulty=?,status=?,updated_at=? WHERE id=?',prompt,solution,JSON.stringify(accepted),explanation,source,difficulty,status,now(),id);await audit('mini-game-round.update',id);return {id};}
  case 'mini-game-round-delete':{const id=String(b.id||'');if(await one("SELECT id FROM mini_game_rooms WHERE status='open' AND json_extract(state,'$.currentId')=? LIMIT 1",id))fail(409,'هذه الجولة مستخدمة الآن. أخفها بدل حذفها.');await run('DELETE FROM mini_game_rounds WHERE id=?',id);await audit('mini-game-round.delete',id);return {ok:true};}
  case 'import':{if(!Array.isArray(b.questions)||b.questions.length<1||b.questions.length>2000)fail(422,'أرسل من سؤال إلى ٢٠٠٠.');const rows=[];for(const raw of b.questions){const q=questionInput(raw);if(!await one('SELECT id FROM tournaments WHERE id=?',q.tournament_id))fail(422,'البطولة غير موجودة.');rows.push(q);}for(let i=0;i<rows.length;i+=60)await db().batch(rows.slice(i,i+60).map(q=>db().prepare('INSERT INTO questions(id,tournament_id,letter,text,answer,difficulty,status,source,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(token(18),q.tournament_id,q.letter,q.text,q.answer,q.difficulty,q.status,q.source,q.note,now(),now())));await audit('questions.import',String(rows.length));return {count:rows.length};}
  case 'tournament':{const name=validName(b.name),position=b.position||0;if(!Number.isInteger(position)||position<0||position>999)fail(422,'ترتيب البطولة غير صحيح.');const id=b.id||token(9);await run('INSERT INTO tournaments(id,name,active,position) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,position=excluded.position',id,name,b.active===false?0:1,position);await audit('tournament.save',id);return {id};}
  case 'close-room':await run("UPDATE rooms SET status='closed',version=version+1 WHERE id=?",String(b.id||''));await audit('room.close',String(b.id||''));return {ok:true};
  case 'close-mini-room':await run("UPDATE mini_game_rooms SET status='closed',version=version+1 WHERE id=?",String(b.id||''));await audit('mini-room.close',String(b.id||''));return {ok:true};
  case 'block-user':await run('UPDATE users SET blocked=? WHERE id=?',b.blocked?1:0,String(b.id||''));if(b.blocked)await run('DELETE FROM sessions WHERE user_id=?',String(b.id||''));await audit('user.block',String(b.id||''));return {ok:true};
  case 'settings':{const supportUrl=normalizeSupportUrl(b.support_url);if(!['light','dark'].includes(b.default_theme)||!Number.isInteger(b.max_players)||b.max_players<2||b.max_players>100||supportUrl===null)fail(422,'راجع الإعدادات. رابط الدعم يجب أن يبدأ بـ https://');await db().batch([['maintenance',b.maintenance?'true':'false'],['default_theme',b.default_theme],['max_players',String(b.max_players)],['support_url',supportUrl]].map(([k,v])=>db().prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,v)));await audit('settings.update');return {ok:true};}
  default:fail(404,'الإجراء غير موجود.');
}}
async function handle(r:Request,{params}:{params:Promise<{path:string[]}>}){const url=new URL(r.url),path='/'+(await params).path.join('/'),method=r.method,ip=r.headers.get('cf-connecting-ip')||'unknown';
  try{
    if(!['GET','POST'].includes(method))fail(405,'الطريقة غير مسموحة.');
    const mediaMatch=method==='GET'&&path.match(/^\/media\/([a-z0-9-]{1,40})$/);
    if(mediaMatch){const item=miniMedia(mediaMatch[1]);if(!item)fail(404,'الصورة غير موجودة.');const cache=(globalThis as any).caches?.default,cacheKey=new Request(url.origin+path);const hit=cache&&await cache.match(cacheKey);if(hit)return hit;const upstream=await fetch(item.url,{headers:{accept:'image/avif,image/webp,image/jpeg,image/*','user-agent':'Huroof-Alkora/1.0'}});if(!upstream.ok)fail(502,'تعذر تحميل الصورة.');const type=upstream.headers.get('content-type')||'';if(!type.startsWith('image/'))fail(502,'صيغة الصورة غير صحيحة.');const bytes=await upstream.arrayBuffer();if(bytes.byteLength>5_000_000)fail(502,'الصورة أكبر من الحد.');const response=new Response(bytes,{headers:{'content-type':type,'cache-control':'public, max-age=604800, s-maxage=2592000, stale-while-revalidate=86400','x-content-type-options':'nosniff','cross-origin-resource-policy':'same-origin'}});if(cache)await cache.put(cacheKey,response.clone());return response;}
    await ensureSeed(url.hostname==='terminal.local');await cleanup();
    if(path==='/health')return json({ok:true,runtime:'worker'});
    const authId=r.headers.get('oai-authenticated-user-id');
    const roomPoll=method==='GET'&&/^\/(?:rooms|mini-rooms)\/[A-Za-z0-9_-]{12}$/.test(path);
    const [context,initialSettings]=await Promise.all([sessionContext(r),settings()]),existingSession=context.session;
    if(roomPoll)await Promise.all([limitPoll('network:'+ip,60000),limitPoll(existingSession?'session:'+existingSession.token_hash:'anonymous:'+ip,existingSession?3000:900)]);
    else await limit('api:'+ip,600,60000);
    let s=existingSession;
    // The owner identity is provisioned in settings; public visitors must never claim it.
    const ownerId=initialSettings.owner_auth_id;
    const admin=authId&&authId===ownerId?{id:authId,username:'يزن',role:'owner'}:null;
    let u=context.user;
    if(path==='/session'&&method==='GET'){
      if(!s){await limit('session:'+ip,120,3600000);const raw=token(),hash=await digest(raw),csrf=token(24),created=now();await run("INSERT INTO sessions(token_hash,kind,user_id,admin_id,expires_at,created_at,csrf) VALUES(?,'guest',NULL,NULL,?,?,?)",hash,created+2592000000,created,csrf);s={token_hash:hash,user_id:null,csrf};return json(await payload(s,admin,null),200,[setCookie('hk_sid',raw,2592000)]);}
      return json(await payload(s,admin,u));
    }
    if(method==='POST'){if(!s)fail(401,'حدّث الصفحة أولًا.');if(r.headers.get('origin')!==url.origin||r.headers.get('x-csrf-token')!==s.csrf||r.headers.get('sec-fetch-site')==='cross-site')fail(403,'تعذر التحقق من الطلب.');}
    if(initialSettings.maintenance==='true'&&!admin&&!['/challenge','/logout'].includes(path))fail(503,'الموقع تحت الصيانة.');
    if(path==='/challenge'&&method==='GET'){
      if(!s)fail(401,'حدّث الصفحة أولًا.');await limit('captcha:'+ip,60,600000);const id=token(18),chars='23456789ABCDEFGHJKLMNPQRSTUVWXYZ',code=Array.from({length:5},()=>chars[crypto.getRandomValues(new Uint8Array(1))[0]%chars.length]).join('');await run('DELETE FROM challenges WHERE session_hash=? OR expires_at<?',s.token_hash,now());await run('INSERT INTO challenges(id,session_hash,answer_hash,expires_at) VALUES(?,?,?,?)',id,s.token_hash,await digest(id+':'+code),now()+120000);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="220" height="76" viewBox="0 0 220 76"><rect width="220" height="76" fill="#f0f4ed"/><path d="M5 18Q60 60 210 9M4 64Q80 1 216 55" stroke="#7e9c8b" fill="none"/><text x="22" y="54" font-family="monospace" font-size="37" font-weight="bold" letter-spacing="4" fill="#163c31">${code}</text></svg>`;return json({id,image:'data:image/svg+xml;base64,'+btoa(svg)});
    }
    if(path==='/identity'&&method==='POST'){
      await limit('identity:'+ip,25,3600000);const b=await body(r,4096),name=validName(b.name),challenge=await one('SELECT * FROM challenges WHERE id=? AND session_hash=?',String(b.challenge||''),s!.token_hash);if(challenge)await run('DELETE FROM challenges WHERE id=?',challenge.id);if(!challenge||challenge.expires_at<now()||challenge.answer_hash!==await digest(challenge.id+':'+String(b.answer||'').toUpperCase()))fail(400,'رمز التحقق غير صحيح.');const id=u?.id||token(18);if(u)await run('UPDATE users SET name=? WHERE id=?',name,id);else await run('INSERT INTO users(id,name,created_at) VALUES(?,?,?)',id,name,now());await db().batch([db().prepare('UPDATE members SET name=? WHERE user_id=?').bind(name,id),db().prepare('UPDATE mini_game_members SET name=? WHERE user_id=?').bind(name,id),db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(s!.token_hash)]);const raw=token(),hash=await digest(raw),csrf=token(24),created=now();await run("INSERT INTO sessions(token_hash,kind,user_id,admin_id,expires_at,created_at,csrf) VALUES(?,'guest',?,NULL,?,?,?)",hash,id,created+2592000000,created,csrf);return json(await payload({csrf},admin,{id,name,theme:u?.theme||'auto'}),200,[setCookie('hk_sid',raw,2592000)]);
    }
    if(path==='/logout'&&method==='POST'){await run('DELETE FROM sessions WHERE token_hash=?',s!.token_hash);return json({ok:true},200,[setCookie('hk_sid','',0)]);}
    if(path==='/tournaments'&&method==='GET')return json(await publicTournaments());
    if(path==='/mini-games'&&method==='GET')return json(await Promise.all(MINI_GAMES.map(async game=>({...game,rounds:Number((await one("SELECT count(*) n FROM mini_game_rounds WHERE game_slug=? AND status='published'",game.slug)).n)}))));
    if(path.startsWith('/admin/')){if(!admin)fail(401,'دخول الإدارة يتطلب حساب مالك الموقع.');await limit('admin:'+admin!.id,240,60000);const name=path.slice('/admin/'.length);if(method==='GET')return json(await adminGet(name,url));if(name==='logout')return json({ok:true});const result=await adminWrite(name,await body(r,1048576));settingsCache=null;tournamentsCache=null;return json(result);}
    if(path==='/profile'){if(!u)fail(401,'ادخل باسمك أولًا.');if(method==='GET')return json({user:{id:u.id,name:u.name,theme:u.theme},stats:await one('SELECT count(*) games,coalesce(sum(won),0) wins FROM match_players WHERE user_id=?',u.id),rooms:(await all("SELECT id,config,created_at FROM rooms WHERE owner_id=? AND status='open' AND expires_at>? ORDER BY created_at DESC LIMIT 20",u.id,now())).map(x=>({...x,config:JSON.parse(x.config)})),miniRooms:(await all("SELECT id,config,created_at FROM mini_game_rooms WHERE owner_id=? AND status='open' AND expires_at>? ORDER BY created_at DESC LIMIT 20",u.id,now())).map(x=>({...x,config:JSON.parse(x.config)}))});const b=await body(r,4096),name=validName(b.name);if(!['light','dark'].includes(b.theme))fail(422,'المظهر غير صحيح.');await db().batch([db().prepare('UPDATE users SET name=?,theme=? WHERE id=?').bind(name,b.theme,u.id),db().prepare('UPDATE members SET name=? WHERE user_id=?').bind(name,u.id),db().prepare('UPDATE mini_game_members SET name=? WHERE user_id=?').bind(name,u.id)]);return json({ok:true});}
    if(path==='/rooms'&&method==='POST'){if(!u)fail(401,'ادخل باسمك أولًا.');await limit('rooms:'+u.id,8,3600000);const c=await configFrom(await body(r,16384)),state=await fresh(c),id=token(9),t=now();await run('INSERT INTO rooms(id,owner_id,config,state,created_at,updated_at,expires_at) VALUES(?,?,?,?,?,?,?)',id,u.id,JSON.stringify(c),JSON.stringify(state),t,t,t+10*60*1000);await run('INSERT INTO events(room_id,message,created_at) VALUES(?,?,?)',id,'بدأت الغرفة',t);return json({id},201);}
    if(path==='/mini-rooms'&&method==='POST'){if(!u)fail(401,'ادخل باسمك أولًا.');await limit('mini-rooms:'+u.id,12,3600000);const c=await miniConfig(await body(r,16384)),state=await miniFresh(c),id=token(9),t=now();await run('INSERT INTO mini_game_rooms(id,owner_id,config,state,created_at,updated_at,expires_at) VALUES(?,?,?,?,?,?,?)',id,u.id,JSON.stringify(c),JSON.stringify(state),t,t,t+MINI_TTL);await run('INSERT INTO mini_game_events(room_id,message,created_at) VALUES(?,?,?)',id,'بدأت اللعبة',t);return json({id},201);}
    const mm=path.match(/^\/mini-rooms\/([A-Za-z0-9_-]{12})(?:\/(action|join|buzz|qr))?$/);if(mm){const id=mm[1],op=mm[2]||'',view=url.searchParams.get('view')||'display';if(!['host','display','buzzer'].includes(view))fail(422,'نوع العرض غير صحيح.');const room=await getMini(id);
      if(!op&&method==='GET'){if(view==='host')miniOwner(room,u);if(view==='buzzer'){await miniMember(room,u);await run('UPDATE mini_game_members SET last_seen=? WHERE room_id=? AND user_id=? AND last_seen<?',now(),id,u!.id,now()-10000);}if(url.searchParams.get('since')===String(room.version))return json({unchanged:true,version:room.version,serverTime:now()});return json(await miniProject(room,view,u));}
      if(op==='qr'&&method==='GET')return json({url:`${url.origin}/mini-room/${id}/buzzer`});
      if(!u)fail(401,'ادخل باسمك أولًا.');if(method!=='POST')fail(405,'الطريقة غير مسموحة.');const b=await body(r);
      if(op==='join'){const team=Number(b.team),existing=await one('SELECT * FROM mini_game_members WHERE room_id=? AND user_id=?',id,u.id);if(existing?.kicked)fail(403,'أزالك المقدم.');if(!existing){const max=Math.max(2,Math.min(200,Number(await setting('max_players','64')))),count=Number((await one('SELECT count(*) count FROM mini_game_members WHERE room_id=? AND kicked=0',id))?.count||0);if(count>=max)fail(409,'اكتمل عدد اللاعبين في الغرفة.');}if(![1,2].includes(team))fail(422,'اختر فريقك.');await run('INSERT INTO mini_game_members(room_id,user_id,team,name,joined_at,last_seen) VALUES(?,?,?,?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET team=excluded.team,name=excluded.name,last_seen=excluded.last_seen',id,u.id,team,u.name,now(),now());await saveMini(room,existing?'':'انضم '+u.name);return json(await miniProject(room,'buzzer',u));}
      if(op==='buzz'){await limit('mini-buzz:'+u.id,6,1000);const p=await miniMember(room,u),s=room.state;if(s.finished||s.revealed||!s.buzz.open||s.buzz.winner||b.key!==s.buzz.key||b.roundKey!==s.roundKey)fail(409,'الجرس مغلق أو سبقك لاعب.');s.buzz={...s.buzz,open:false,winner:{id:p.user_id,name:p.name,team:p.team},deadline:now()+room.config.seconds*1000};await saveMini(room,'ضغط '+p.name+' الجرس');return json({ok:true});}
      if(op==='action'){await limit('mini-action:'+u.id,160,60000);return json(await miniAction(room,u,b));}
    }
    const m=path.match(/^\/rooms\/([A-Za-z0-9_-]{12})(?:\/(action|join|buzz|events|qr))?$/);if(m){const id=m[1],op=m[2]||'',view=url.searchParams.get('view')||'display';if(!['host','display','buzzer'].includes(view))fail(422,'نوع العرض غير صحيح.');let room=await expire(await getRoom(id));
      if(!op&&method==='GET'){if(view==='host')owner(room,u);if(view==='buzzer'){await member(room,u);await run('UPDATE members SET last_seen=? WHERE room_id=? AND user_id=? AND last_seen<?',now(),id,u!.id,now()-10000);}if(url.searchParams.get('since')===String(room.version))return json({unchanged:true,version:room.version,serverTime:now()});return json(await project(room,view,u));}
      if(op==='events'&&method==='GET'){const data=await project(room,view,u);return new Response(`retry: 500\nevent: state\ndata: ${JSON.stringify(data)}\n\n`,{headers:{'content-type':'text/event-stream; charset=utf-8','cache-control':'no-store'}});}
      if(op==='qr'&&method==='GET')return json({error:'QR غير متاح مؤقتًا'},501);
      if(!u)fail(401,'ادخل باسمك أولًا.');if(method!=='POST')fail(405,'الطريقة غير مسموحة.');const b=await body(r);
      if(op==='join'){const team=b.team,existing=await one('SELECT * FROM members WHERE room_id=? AND user_id=?',id,u.id);if(existing?.kicked)fail(403,'أزالك المقدم.');if(![1,2].includes(team))fail(422,'اختر فريقك.');if(existing&&existing.team!==team&&room.state.board.some((c:Row)=>c.owner))fail(409,'لا يمكن تغيير الفريق الآن.');if(!existing&&(await members(id)).length>=Number(await setting('max_players','64')))fail(409,'الغرفة مكتملة.');await run('INSERT INTO members(room_id,user_id,team,name,joined_at,last_seen) VALUES(?,?,?,?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET name=excluded.name,team=excluded.team,last_seen=excluded.last_seen',id,u.id,team,u.name,now(),now());await save(room,existing?'':'انضم '+u.name);return json(await project(room,'buzzer',u));}
      if(op==='buzz'){await limit('buzz:'+u.id,6,1000);const p=await member(room,u),s=room.state;if(!s.current||s.revealed||!s.buzz.open||s.buzz.winner||b.key!==s.buzz.key||b.questionKey!==s.questionKey)fail(409,'الجرس مغلق أو سبقك لاعب.');s.buzz.open=false;s.buzz.winner={id:p.user_id,name:p.name,team:p.team};s.buzz.deadline=now()+room.config.seconds*1000;await save(room,'ضغط '+p.name+' الجرس');return json(await project(room,'buzzer',u,true));}
      if(op==='action'){await limit('action:'+u.id,160,60000);return json(await act(room,u,b));}
    }
    fail(404,'الصفحة غير موجودة.');
  }catch(e:any){if((e.status||500)>=500)console.error('Huroof API error',e);const previewDetail=url.hostname==='terminal.local'?String(e?.message||e):'';return json({error:e.status?e.message:previewDetail||'حدث خطأ مؤقت في الموقع.'},e.status||500);}
}
export const GET=handle;
export const POST=handle;
